set tool "mpl"
set exp_internal 1
set gradeup1 "a= 5 7 3 8; a\[>a\]"
set gradedn1 "a= 5 7 3 8; a\[<a\]"
set mmpy    "(3 4#::12) \\* 4 2#::8"
set mmpyinv    "a = (2 2)#1 11 3 8; b = \\/a; a\\*b"
set mmpvm      "a = 1 2 3; b = 3 2#::6;  a\\*b"
set mmpmv      "(3 2 #::6)\\*1 2"
set solvemm    "(2 2#4::7) \\/ 2 2#1::4"
set solvemv    "(2 2#4::7) \\/ 1::2"
set solvevm    "(1 2) \\/ (2 2#4::7)"
set summtx     "/+2 3#::6"
set sumvec     "/+::6"
set sumscalar  "/+6"
set prodmtx     "/*2 3#1::6"
set prodvec     "/*1::6"
set prodscalar  "/*6"
set tpose       "$ 2 3#1::6"

# matrix[vector]
set index1 "a=2 3#::6; a\[ 1 1 \]"

# vector[scalar]
set index2 "a=::6; a\[ 3 \]"

# vector[vector]
set index3 "a=::6; a\[ 1 3 \]"

# vector[matrix]
set index4 "a=::6; a\[ 2 2#::4 \]"

# matrix[matrix]           TODO

#set xfail_flag 1

set testdata {
    {"\"$tpose\""   ".*\n1 4.*\n2 5.*\n3 6"}
    {"\"$prodscalar\""   "6"}
    {"\"$prodvec\""   "720"}
    {"\"$prodmtx\""   "720"}
    {"\"$sumscalar\""   "6"}
    {"\"$sumvec\""   "15"}
    {"\"$summtx\""   "15"}
    {"\"$solvemv\""   "16 19"}
    {"\"$solvevm\""   "14 20"}
    {"\"$solvemm\""   ".*\n-0.5 1.5.*\n-1.5 2.5"}
    {"\"$mmpmv\""   "2 8 14"}
    {"\"$mmpvm\""   "16 22"}
    {"\"$mmpyinv\""   ".*\n1 0.*\n0 1"}
    {"\"det (3 3)#1 4 3 8 5 2 9 4 7\"" "-164"}
    {"\"$index1\""           "4" }
    {"\"$index2\""           "3" }
    {"\"$index3\""           "3" }
    {"\"$index4\""           "0 1.*\n2 3" }
    {"\"$mmpy\""   ".*\n28 34.*\n76 98.*\n124 162"}

    {"\"/.5\""           "2" }
    {"\"-5\""           "-5" }
    {"\"-~5\""           "5" }
    {"\"$ 2 3#::6\""    "0 3.*\n1 4.*\n2 5" }
    {"\"ln e^2\""        "2" }
    {"\"log 10^2\""        "2" }
    {"\"ln exp 2\""        "2" }
    {"\"root 4\""        "2" }
    {"\"sin pi / 6\""     "0.5" }
    {"\"cos 2*pi / 6\""     "0.5" }
    {"\"tan pi / 4\""     "1" }
    {"\"asin sin 1\""     "1" }
    {"\"acos cos 1\""     "1" }
    {"\"atan tan 1\""     "1" }
    {"\"sind 30\""     "0.5" }
    {"\"cosd 60\""     "0.5" }
    {"\"tand 45\""     "1" }
    {"\"asind sind 1\""     "1" }
    {"\"acosd cosd 1\""     "1" }
    {"\"atand tand 1\""     "1" }
    {"\"|~1\""     "1" }
    {"\"|1\""     "1" }
    {"\"!5\""     "120" }
    {"\"ceil 1.5\""     "2" }
    {"\"floor 1.5\""    "1" }
    {"\"round 1.6\""    "2" }
    {"\"round 1.4\""    "1" }
    {"\"> 5 7 3 8\""    "2 0 1 3" }
    {"\"$gradeup1\""    "3 5 7 8" }
    {"\"< 5 7 3 8\""    "3 1 0 2" }
    {"\"$gradedn1\""    "8 7 5 3" }
    {"\"#2 3#::6\""    "2 3" }
    {"\"::6\""    "0 1 2 3 4 5" }
    
    {"\"2*3\""           "6" }
    {"\"3/2\""         "1.5" }
    {"\"(2+3)\""         "5" }
    {"\"2-3\""          "-1" }
    {"\"(1 0) $ 2 3#::6\""    "0 3.*\n1 4.*\n2 5" }
    {"\"2^3\""          "8" }
    {"\"10 log 100\""      "2" }
    {"\"e log e\""      "1" }
    {"\"3 root 8\""      "2" }
    {"\"inf atan 1\""      "0" }
    {"\"1 atand 1\""      "45" }
    {"\"a=4;a\""      "4" }
    {"\"2 3#::6\""    "0 1 2.*\n3 4 5" }
    {"\"6::4\""    "6 5 4" }
    {"\"4::6\""    "4 5 6" }
    {"\"4::6\""    "4 5 6" }
    {"\"4?=4\""    "true" }
    {"\"4?=6\""    "false" }
    {"\"4?<4\""    "false" }
    {"\"4?<6\""    "true" }
    {"\"6?<4\""    "false" }
    {"\"4?>4\""    "false" }
    {"\"4?>6\""    "false" }
    {"\"6?>4\""    "true" }
    {"\"4?<=4\""    "true" }
    {"\"4?<=6\""    "true" }
    {"\"6?<=4\""    "false" }
    {"\"4?>=4\""    "true" }
    {"\"4?>=6\""    "false" }
    {"\"6?>=4\""    "true" }
}

global MPL
foreach pattern $testdata {
    set inputs [lindex $pattern 0]
    eval "spawn $MPL --test-mode -e $inputs"
    expect {
        -re [lindex $pattern 1] {
            pass $inputs
        }
        default { fail $inputs}
    }
}
      
